# VERSION: 2

BATCH_SIZE: 4
SOLVER:
  NAME: "Adam" # Adam or SGD
  WARMUP_ITERS: 100 # Set to 0 for no warmup
  # ACCUMULATE_GRAD: 2 # Number of accumulated epochs for accumulated gradient
  FAST_DEV_RUN: 2
  BASE_LR: 0.0001
  N_EPOCHS: 700
  INIT_WEIGHTS: True
  

CHECKPOINT_PATH_TRAINING: ""
CHECKPOINT_PATH_INFERENCE: ""

ANOMALY_DATASET:
  PREVIEW_DATASET: False
  MAX_SAMPLES: null #Number of training samples, null for all
  SHUFFLE: True
  MAX_SIZE: 256
  ANOMALY_FOLDER: "" #e.g. "blanded" or leave empty "" to use all anomaly folders
  DATASET_PATH:
    ROOT: "datasets"
    ANOMALY_SOURCE: "dtd/images"
    MVTEC: "mvtec"
    